#!/usr/bin/env python3
"""Translate src/math/double_math_tables.rs into gpu/sim/double_tables.h.

Only bit patterns are copied, so the GPU tables equal the CPU ones exactly.
"""
import argparse
from pathlib import Path
import re
import sys

HERE = Path(__file__).resolve().parent
source = (HERE.parent / "src/math/double_math_tables.rs").read_text()
out = [
    "// Generated by gpu/gen_tables.py from src/math/double_math_tables.rs. Do not edit.",
    "#pragma once",
    "#include <cstdint>",
]


def c_type(rust):
    dims = []
    while rust.startswith("["):
        inner, count = re.fullmatch(r"\[(.*);(\d+)\]", rust).groups()
        dims.insert(0, count)
        rust = inner
    base = {"f64": "double", "u64": "uint64_t"}[rust]
    return base, "".join(f"[{d}]" for d in reversed(dims))


def c_value(rust, top_level=True):
    """Keep the header layout independent of Rust source formatting."""
    rust = re.sub(r"\s+", "", rust)
    if rust.startswith("["):
        values = []
        start = 1
        depth = 0
        for index, char in enumerate(rust[1:-1], start=1):
            if char in "[(":
                depth += 1
            elif char in "])":
                depth -= 1
            elif char == "," and depth == 0:
                values.append(c_value(rust[start:index], False))
                start = index + 1
        if start < len(rust) - 1:
            values.append(c_value(rust[start:-1], False))
        separator = ",\n" if top_level else ","
        edge = "\n" if top_level else ""
        return "{" + edge + separator.join(values) + edge + "}"
    if match := re.fullmatch(r"f64::from_bits\((0x[0-9a-f]+)\)", rust):
        return f"__builtin_bit_cast(double, (uint64_t){match[1]}ull)"
    if re.fullmatch(r"0x[0-9a-f]+|0", rust):
        return rust + "ull"
    raise ValueError(f"unsupported table value: {rust}")


for name, rust_type, value in re.findall(r"pub(?:\([^)]*\))? const (\w+): ([^=]+?) = (.*?);\n", source, re.S):
    base, dims = c_type(rust_type.replace(" ", ""))
    value = c_value(value)
    out.append(f"__device__ constexpr {base} {name}{dims} = {value};")

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--output", type=Path, default=HERE / "sim/double_tables.h")
parser.add_argument("--check", action="store_true", help="check the selected header without writing it")
args = parser.parse_args()
generated = "\n".join(out) + "\n"
if args.check:
    if not args.output.is_file() or args.output.read_text() != generated:
        parser.exit(1, f"{args.output} is stale; run python3 gpu/gen_tables.py\n")
    print(f"verified {args.output}", file=sys.stderr)
else:
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)
    print(f"wrote {args.output}", file=sys.stderr)
