#!/usr/bin/env python3
"""Translate src/double_math_tables.rs into gpu/sim/double_tables.h.

Only bit patterns are copied, so the GPU tables equal the CPU ones exactly.
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
source = (HERE.parent / "src/double_math_tables.rs").read_text()
out = [
    "// Generated by gpu/gen_tables.py from src/double_math_tables.rs. Do not edit.",
    "#pragma once",
    "#include <cstdint>",
]


def c_type(rust):
    dims = []
    while rust.startswith("["):
        inner, count = re.fullmatch(r"\[(.*);(\d+)\]", rust).groups()
        dims.insert(0, count)
        rust = inner
    base = {"f64": "double", "u64": "uint64_t"}[rust]
    return base, "".join(f"[{d}]" for d in reversed(dims))


for name, rust_type, value in re.findall(r"pub const (\w+): ([^=]+?) = (.*?);\n", source, re.S):
    base, dims = c_type(rust_type.replace(" ", ""))
    value = re.sub(r"f64::from_bits\((0x[0-9a-f]+)\)", r"__builtin_bit_cast(double, (uint64_t)\1ull)", value)
    if base == "uint64_t":
        value = re.sub(r"\b(0x[0-9a-f]+|0)\b", r"\1ull", value)
    value = value.replace("[", "{").replace("]", "}")
    out.append(f"__device__ constexpr {base} {name}{dims} = {value};")

target = HERE / "sim/double_tables.h"
target.write_text("\n".join(out) + "\n")
print(f"wrote {target}", file=sys.stderr)
