// Generated by examples/gpu_engine_scan.rs: every float with |x| <= 16 whose
// engine_sin_cos_raw result differs from x87 FSINCOS. Keys: input bits, sorted.
#pragma once
#include <cstdint>
constexpr int ENGINE_EXCEPTION_COUNT = 0;
constexpr int ENGINE_EXCEPTION_STEP = 0;
__device__ constexpr uint32_t ENGINE_EXCEPTIONS[1][3] = {
    {0, 0, 0},
};
