// Generated by wasm/gen-sim.py; offsets match generated.wgsl raw loaders.
use super::append_ptr;
use crate::gpu_sim::WorldDesc;
pub(super) fn encode_world(w: &WorldDesc) -> Result<Vec<u32>, String> {
    let mut data = vec![0u32; 64];
    data[0] = w.ray_node_count;
    data[1] = w.ray_wall_count;
    data[2] = w.ray_depth;
    data[3] = w.ray_magnitude.to_bits();
    data[4] = unsafe { append_ptr(&mut data, w.ray_nodes, w.ray_node_count as usize) }?;
    data[5] = unsafe { append_ptr(&mut data, w.ray_walls, w.ray_wall_count as usize) }?;
    data[6] = w.surface_count;
    data[7] = w.default_surface;
    data[8] = unsafe { append_ptr(&mut data, w.surfaces, w.surface_count as usize) }?;
    data[9] = i32::try_from(w.tile_x0).map_err(|_| "tile bounds exceed WebGPU range")? as u32;
    data[10] = i32::try_from(w.tile_y0).map_err(|_| "tile bounds exceed WebGPU range")? as u32;
    data[11] = i32::try_from(w.tile_nx).map_err(|_| "tile bounds exceed WebGPU range")? as u32;
    data[12] = i32::try_from(w.tile_ny).map_err(|_| "tile bounds exceed WebGPU range")? as u32;
    data[13] = unsafe {
        append_ptr(
            &mut data,
            w.tiles,
            (w.tile_nx as usize)
                .checked_mul(w.tile_ny as usize)
                .ok_or("tile count overflow")?,
        )
    }?;
    data[14] = w.path_points;
    data[15] = w.pad0;
    data[16] = unsafe {
        append_ptr(
            &mut data,
            w.path_segments,
            w.path_points.saturating_sub(1) as usize,
        )
    }?;
    data[17] = unsafe { append_ptr(&mut data, w.path_offsets, w.path_points as usize) }?;
    let cells = (w.path_grid.nx as usize)
        .checked_mul(w.path_grid.ny as usize)
        .ok_or("grid count overflow")?;
    let count_path_grid = if cells > 0 {
        unsafe { *w.path_grid.start.add(cells) as usize }
    } else {
        0
    };
    let bits = w.path_grid.x0.to_bits();
    data[18] = bits as u32;
    data[19] = (bits >> 32) as u32;
    let bits = w.path_grid.y0.to_bits();
    data[20] = bits as u32;
    data[21] = (bits >> 32) as u32;
    let bits = w.path_grid.cell.to_bits();
    data[22] = bits as u32;
    data[23] = (bits >> 32) as u32;
    data[24] = w.path_grid.nx;
    data[25] = w.path_grid.ny;
    data[26] = unsafe {
        append_ptr(
            &mut data,
            w.path_grid.start,
            if cells > 0 { cells + 1 } else { 0 },
        )
    }?;
    data[27] = unsafe { append_ptr(&mut data, w.path_grid.items, count_path_grid) }?;
    data[28] = w.curve_points;
    data[29] = w.curve_length.to_bits();
    data[30] = unsafe { append_ptr(&mut data, w.curve_position, w.curve_points as usize) }?;
    data[31] = unsafe { append_ptr(&mut data, w.curve_offsets, w.curve_points as usize) }?;
    data[32] = unsafe { append_ptr(&mut data, w.curve_forwards, w.curve_points as usize) }?;
    let cells = (w.curve_grid.nx as usize)
        .checked_mul(w.curve_grid.ny as usize)
        .ok_or("grid count overflow")?;
    let count_curve_grid = if cells > 0 {
        unsafe { *w.curve_grid.start.add(cells) as usize }
    } else {
        0
    };
    let bits = w.curve_grid.x0.to_bits();
    data[34] = bits as u32;
    data[35] = (bits >> 32) as u32;
    let bits = w.curve_grid.y0.to_bits();
    data[36] = bits as u32;
    data[37] = (bits >> 32) as u32;
    let bits = w.curve_grid.cell.to_bits();
    data[38] = bits as u32;
    data[39] = (bits >> 32) as u32;
    data[40] = w.curve_grid.nx;
    data[41] = w.curve_grid.ny;
    data[42] = unsafe {
        append_ptr(
            &mut data,
            w.curve_grid.start,
            if cells > 0 { cells + 1 } else { 0 },
        )
    }?;
    data[43] = unsafe { append_ptr(&mut data, w.curve_grid.items, count_curve_grid) }?;
    data[44] = w.shape_count;
    data[45] = w.shape_point_count;
    data[46] = unsafe { append_ptr(&mut data, w.shapes, w.shape_count as usize) }?;
    data[47] = unsafe { append_ptr(&mut data, w.shape_local, w.shape_point_count as usize) }?;
    data[48] = unsafe { append_ptr(&mut data, w.shape_normals, w.shape_point_count as usize) }?;
    let cells = (w.shape_grid.nx as usize)
        .checked_mul(w.shape_grid.ny as usize)
        .ok_or("grid count overflow")?;
    let count_shape_grid = if cells > 0 {
        unsafe { *w.shape_grid.start.add(cells) as usize }
    } else {
        0
    };
    let bits = w.shape_grid.x0.to_bits();
    data[50] = bits as u32;
    data[51] = (bits >> 32) as u32;
    let bits = w.shape_grid.y0.to_bits();
    data[52] = bits as u32;
    data[53] = (bits >> 32) as u32;
    let bits = w.shape_grid.cell.to_bits();
    data[54] = bits as u32;
    data[55] = (bits >> 32) as u32;
    data[56] = w.shape_grid.nx;
    data[57] = w.shape_grid.ny;
    data[58] = unsafe {
        append_ptr(
            &mut data,
            w.shape_grid.start,
            if cells > 0 { cells + 1 } else { 0 },
        )
    }?;
    data[59] = unsafe { append_ptr(&mut data, w.shape_grid.items, count_shape_grid) }?;
    let bits = w.shape_margin.to_bits();
    data[60] = bits as u32;
    data[61] = (bits >> 32) as u32;
    data[62] = unsafe { append_ptr(&mut data, w.path_xy, w.path_points as usize * 2) }?;
    Ok(data)
}
