//! Exhaustive comparison of the GPU engine sine/cosine (gpu/sim/math.h
//! engine_sin_cos_raw) with x87 FSINCOS for every float with |x| <= 16.
//! Write mismatches to the requested header; install it and rebuild explicitly.
//! The exhaustive scan covers over two billion inputs and may take several minutes.
//! Usage: gpu_engine_scan THREADS OUT_HEADER
use altd_sim::gpu::hip::Gpu;
use altd_sim::math::native_math::engine_sin_cos;
use std::io::Write;
use std::time::Instant;

const LIMIT_BITS: u32 = 0x4180_0000; // 16.0f32, matches ENGINE_DOMAIN
const CHUNK: u32 = 1 << 24;

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.len() != 2 || args[0] == "--help" {
        eprintln!("usage: gpu_engine_scan THREADS OUT_HEADER");
        if args.first().is_some_and(|a| a == "--help") {
            return;
        }
        std::process::exit(2);
    }
    let threads: usize = args[0].parse().expect("threads");
    assert!(threads > 0, "threads must be positive");
    let out_path = &args[1];
    let gpu = Gpu::open(None).unwrap_or_else(|e| panic!("{e}"));
    let started = Instant::now();
    let mut exceptions: Vec<[u32; 3]> = Vec::new();
    let mut gpu_out = vec![[0u32; 2]; CHUNK as usize];
    let total = 2 * (LIMIT_BITS as u64 + 1);
    let mut done = 0u64;
    for sign in [0u32, 0x8000_0000] {
        let mut first = 0u32;
        while first <= LIMIT_BITS {
            let n = CHUNK.min(LIMIT_BITS + 1 - first);
            let out = &mut gpu_out[..n as usize];
            gpu.engine_scan(sign | first, out);
            let per = (n as usize).div_ceil(threads);
            let found: Vec<Vec<[u32; 3]>> = std::thread::scope(|scope| {
                let handles: Vec<_> = out
                    .chunks(per)
                    .enumerate()
                    .map(|(t, part)| {
                        let base = sign | (first + (t * per) as u32);
                        scope.spawn(move || {
                            let mut local = Vec::new();
                            for (i, &[s, c]) in part.iter().enumerate() {
                                let bits = base + i as u32;
                                let (xs, xc) = engine_sin_cos(f32::from_bits(bits));
                                if xs.to_bits() != s || xc.to_bits() != c {
                                    local.push([bits, xs.to_bits(), xc.to_bits()]);
                                }
                            }
                            local
                        })
                    })
                    .collect();
                handles.into_iter().map(|h| h.join().unwrap()).collect()
            });
            for part in found {
                exceptions.extend(part);
            }
            done += n as u64;
            first += n;
            if first.is_multiple_of(CHUNK * 8) || first > LIMIT_BITS {
                let elapsed = started.elapsed().as_secs_f64();
                eprintln!(
                    "{:5.1}%  {} exceptions  {:.0} s elapsed, ~{:.0} s left",
                    100.0 * done as f64 / total as f64,
                    exceptions.len(),
                    elapsed,
                    elapsed * (total - done) as f64 / done as f64
                );
            }
        }
    }
    exceptions.sort_by_key(|e| e[0]);
    let count = exceptions.len();
    let step = if count <= 1 {
        0
    } else {
        1usize << (usize::BITS - 1 - (count - 1).leading_zeros())
    };
    let mut header = String::new();
    header.push_str("// Generated by examples/gpu_engine_scan.rs: every float with |x| <= 16 whose\n");
    header.push_str("// engine_sin_cos_raw result differs from x87 FSINCOS. Keys: input bits, sorted.\n");
    header.push_str("#pragma once\n#include <cstdint>\n");
    header.push_str(&format!("constexpr int ENGINE_EXCEPTION_COUNT = {count};\n"));
    header.push_str(&format!("constexpr int ENGINE_EXCEPTION_STEP = {step};\n"));
    header.push_str(&format!(
        "__device__ constexpr uint32_t ENGINE_EXCEPTIONS[{}][3] = {{\n",
        count.max(1)
    ));
    if exceptions.is_empty() {
        header.push_str("    {0, 0, 0},\n");
    }
    for [x, s, c] in &exceptions {
        header.push_str(&format!(
            "    {{0x{x:08x}u, 0x{s:08x}u, 0x{c:08x}u}},  // {:e}\n",
            f32::from_bits(*x)
        ));
    }
    header.push_str("};\n");
    std::fs::File::create(out_path)
        .and_then(|mut f| f.write_all(header.as_bytes()))
        .expect("write header");
    println!(
        "{count} exceptions of {total} inputs written to {out_path} in {:.0} s",
        started.elapsed().as_secs_f64()
    );
}
